# Generated by Django 5.2.7 on 2025-10-06 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_telegramnotification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramnotification",
            name="from_url",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Адрес отправки"
            ),
        ),
        migrations.AlterField(
            model_name="authtoken",
            name="token",
            field=models.CharField(
                default=uuid.UUID("d64edf62-f5fe-4637-970f-97b629b2cdd6"),
                max_length=40,
                unique=True,
                verbose_name="Токен",
            ),
        ),
        migrations.AlterField(
            model_name="telegramnotification",
            name="message",
            field=models.CharField(max_length=256, verbose_name="Сообщение"),
        ),
    ]
