# Generated by Django 5.2.7 on 2025-11-12 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_telegramnotification_from_url_alter_authtoken_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="products",
        ),
        migrations.AlterField(
            model_name="authtoken",
            name="token",
            field=models.CharField(
                default=uuid.UUID("7286beab-acdd-4fa4-93b0-6562f3f4b15b"),
                max_length=40,
                unique=True,
                verbose_name="Токен",
            ),
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="main.menu",
                        verbose_name="Меню",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.product",
                        verbose_name="Блюдо",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция в меню",
                "verbose_name_plural": "Позиция в меню",
            },
        ),
    ]
