# Generated by Django 5.2.7 on 2025-11-12 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_menu_products_alter_authtoken_token_menuitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproduct",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AlterField(
            model_name="authtoken",
            name="token",
            field=models.CharField(
                default=uuid.UUID("5501b69d-2392-4e20-9e8e-1721f28c9e34"),
                max_length=40,
                unique=True,
                verbose_name="Токен",
            ),
        ),
    ]
