# Generated by Django 5.2.7 on 2025-11-12 08:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_historicalproduct_price_remove_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authtoken",
            name="token",
            field=models.CharField(
                default=uuid.UUID("c1dbf705-a48e-4e7e-8f9f-eb389dd0d583"),
                max_length=40,
                unique=True,
                verbose_name="Токен",
            ),
        ),
    ]
